apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rojandincse.fullname" . }}
  labels:
    {{- include "rojandincse.labels" . | nindent 4 }}
data:
  nginx.conf: |
    {{- toYaml .Values.config | nindent 4 }}
