image:
  repository: registry-docker-registry:5000/rojandincse
  tag: latest

ingress:
  enabled: true
  className: nginx
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "rojandinc.se,www.rojandinc.se"
    external-dns.alpha.kubernetes.io/target: tunnel.rojandinc.se
    nginx.ingress.kubernetes.io/enable-global-auth: "false"

  hosts:
    - host: rojandinc.se
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: www.rojandinc.se
      paths:
        - path: /
          pathType: ImplementationSpecific

service:
  port: 80

resources:
  requests:
    cpu: 10m
    memory: 64Mi

autoscaling:
  enabled: true


livenessProbe:
  httpGet:
    path: /health
    port: 80
  initialDelaySeconds: 3
  periodSeconds: 3

readinessProbe:
  httpGet:
    path: /health
    port: 80
  initialDelaySeconds: 3
  periodSeconds: 3
