image:
  repository: registry-docker-registry:5000/rojandincse
  tag: latest

config: |
  server {
    listen 80;
    server_name frontend;
    location / {
     root /usr/share/nginx/html;
     try_files $uri /index.html;
    }

    location = /health {
      access_log off;
      add_header 'Content-Type' 'application/json';
      return 200 '{"status":"ok"}';
    }
  }


ingress:
  enabled: true
  className: nginx
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "www.rojandinc.se"
    external-dns.alpha.kubernetes.io/target: tunnel.rojandinc.se
    nginx.ingress.kubernetes.io/enable-global-auth: "false"

  hosts:
    - host: www.rojandinc.se
      paths:
        - path: /
          pathType: ImplementationSpecific

service:
  port: 80

resources:
  requests:
    cpu: 10m
    memory: 64Mi

autoscaling:
  enabled: true


livenessProbe:
  httpGet:
    path: /health
    port: 80
  initialDelaySeconds: 3
  periodSeconds: 3

readinessProbe:
  httpGet:
    path: /health
    port: 80
  initialDelaySeconds: 3
  periodSeconds: 3
