backend:
  name: github
  repo: rojanDinc/rojandinc.se

media_folder: static/assets
public_folder: assets

collections:
  - name: projects
    label: Projects
    folder: posts/projects
    create: true
    identifier_field: projects
    fields:
      - {
          label: 'Page type',
          name: 'pagetype',
          widget: 'hidden',
          default: 'project-post',
        }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - {
          name: images,
          label: Images,
          widget: list,
          field: { name: image, label: Image, widget: image },
        }
      - { name: alt, label: Alt attribute }
      - { name: body, label: Body, widget: text }
  - name: technologies
    label: Technologies
    folder: posts/technologies
    create: true
    identifier_field: technologies
    fields:
      - {
          label: 'Page type',
          name: 'pagetype',
          widget: 'hidden',
          default: 'technology-post',
        }
      - { name: title, label: Title }
      - { name: image, label: Image, widget: image }
      - { name: alt, label: Alt attribute }
  - name: experiences
    label: Experiences
    folder: posts/experiences
    create: true
    identifier_field: experiences
    fields:
      - {
          label: 'Page type',
          name: 'pagetype',
          widget: 'hidden',
          default: 'experience-post',
        }
      - { name: title, label: Title }
      - { name: from, label: From, widget: date }
      - { name: to, label: To, widget: date }
      - { name: body, label: Body, widget: markdown }
      - {
          name: images,
          label: Images,
          widget: list,
          field: { name: image, label: Image, widget: image },
        }
      - { name: alt, label: Alt attribute }
  - name: services
    label: Services
    folder: posts/services
    create: true
    identifier_field: services
    fields:
      - {
          label: 'Page type',
          name: 'pagetype',
          widget: 'hidden',
          default: 'service-post',
        }
      - {
          name: servicetype,
          label: Service Type,
          widget: select,
          multiple: true,
          options: ['web', 'system', 'mobile'],
        }
      - { name: title, label: Title }
      - { name: image, label: Image, widget: image }
      - { name: alt, label: Alt attribute }
      - { name: date, label: Date }
